title: Robotics Engineer
author: Sushma
email: sushmachandra2023@u.northwestern.edu
description: >-
  Hi, I'm currently a graduate student in the MS in Robotics program at Northwestern University.
  These were some of my cool projects. I'm passionate about autonomous systems, computer vision, 
  AI, robotic manipulator, and navigation. 

social:
  github: suzie13
  linkedin: sushma-s-chandra

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true


url: suzie13.github.io
baseurl: /Sushma_S_Chandra
