title: Robotics Engineer
author: Sushma
email: sushmachandra2023@u.northwestern.edu
description: >-
  Hi, I graduated with an MS in Robotics from Northwestern University. Thereafter, I did an internship
  at SonyAI, for 6 months duration, as Robotics Software Engineering Intern.
  You just saw some of my cool projects. I'm passionate about autonomous cognitive systems,
  robot manipulation, motion planning, integration, navigation, perception and AI.

social:
  github: suzie13
  linkedin: sushma-s-chandra

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true


url: suzie13.github.io
baseurl: /Sushma_S_Chandra
